server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hacktheinterview
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # The SQL dialect makes Hibernate generate better SQL for the chosen database