server:
  port: ${SERVER_PORT:9999}

spring:
  datasource:
    url: ${DB_HOST:jdbc:mysql://localhost}:${DB_PORT:3306}/${DB_NAME:hacktheinterview}
    username: ${DB_USER:root}
    password: ${DB_PWD:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect # The SQL dialect makes Hibernate generate better SQL for the chosen database