server:
  port: ${SERVER_PORT:9999}

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 295110977444-tkc3l6lqfhkfuovk1bmqlrhnoa02ap88.apps.googleusercontent.com
            client-secret: bTWSC6KJdNZufUg-479r_ZpQ
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:hack_the_interview
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

spa:
  patterns:
    - /
    - /404/