server:
  port: ${SERVER_PORT:9999}

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:hack_the_interview
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect